### ISSUE TITLE
There is no default $binaryPathConfigKey available

### ISSUE THREAD

**Issue by hoekstramenno** [LukeTowers/oc-snappypdf-plugin#3]
I want to use my own SNAPPY_PDF_BINARY in my .env-file like this:
`SNAPPY_PDF_BINARY=/usr/local/bin/wkhtmltopdf`

If I want to download a pdf from a controller it does not find this new path. Instead I got

```Undefined variable: binaryPathConfigKey on  .../plugins/luketowers/snappypdf/Plugin.php line 116```

**Comment by LukeTowers** [comment]
Fixed by #7
