### ISSUE TITLE
I can not install the plugin

### ISSUE THREAD

**Issue by mihailbishkek** [LukeTowers/oc-snappypdf-plugin#5]
I tried all the ways, and it’s impossible to install. Please, help....

Composer return error: 

![изображение](https://user-images.githubusercontent.com/18412931/59052653-551c0780-88b1-11e9-9975-f1c4d6e775a3.png)

Plugin after install return: 
![изображение](https://user-images.githubusercontent.com/18412931/59052789-b8a63500-88b1-11e9-8a7e-6709cb64e8c8.png)

**Comment by LukeTowers** [comment]
@mihailbishkek looks like you're using Windows. You can try using the Windows branch of the plugin https://github.com/LukeTowers/oc-snappypdf-plugin/tree/windows-support and see if you can get that working fully. If you can, then please make any required PRs and confirm that the branch is ready to be merged into master.

**Comment by mihailbishkek** [comment]
@LukeTowers Yes, I am use it on Windows.

I clone windows-support tree, and install this package to `plugins\luketowers\snappypdf\vendor\wkhtmltopdf\`
![изображение](https://user-images.githubusercontent.com/18412931/59081796-d60aeb80-8911-11e9-8b5f-e33ca6597dbb.png)

I just have this error: 
![изображение](https://user-images.githubusercontent.com/18412931/59081849-1b2f1d80-8912-11e9-8081-fa750670f60e.png)

**Comment by mihailbishkek** [comment]
My config is

```'config' => [
                'pdf' => array(
                    'enabled' => true,
                    'binary'  => env('SNAPPY_PDF_BINARY', plugins_path('luketowers/snappypdf/vendor/wkhtmltopdf/bin/wkhtmltopdf.exe')),
                    'timeout' => false,
                    'options' => array(),
                    'env'     => array(),
                ),
                'image' => array(
                    'enabled' => true,
                    'binary'  => env('SNAPPY_IMAGE_BINARY', plugins_path('luketowers/snappypdf/vendor/wkhtmltopdf/bin/wkhtmltoimage.exe')),
                    'timeout' => false,
                    'options' => array(),
                    'env'     => array(),
                ),
            ],```

**Comment by LukeTowers** [comment]
@mihailbishkek did you try running `php artisan october:env` to generate a .env file and then specifying the config using ENV vars instead of the config file? It's possible that the config file isn't properly used when detecting the binary path to use while the .env file is fully supported.

**Comment by mihailbishkek** [comment]
![изображение](https://user-images.githubusercontent.com/18412931/59082261-0eabc480-8914-11e9-8e01-e81b8394360a.png)

**Comment by mihailbishkek** [comment]
I make .env file. And now I have this error: 

![изображение](https://user-images.githubusercontent.com/18412931/59083117-d4dcbd00-8917-11e9-91d3-38341a64fe4f.png)

**Comment by LukeTowers** [comment]
@mihailbishkek make sure that the path is an absolute path, you're still using a local one.
