### ISSUE TITLE
Can't make it work with example code from plugin page.

### ISSUE THREAD

**Issue by Zmove** [LukeTowers/oc-snappypdf-plugin#6]
Hello,

I try to make SnappyPDF to work, but I'm becoming crazy trying things that doesn't work.

I have a button on backend that trigger a `onDownloadFile()` function, here is my function

    public function onDownloadFile() {
        trace_log('test');
        $renderedHtml = '<h1>Test</h1>';
        $pdf = SnappyPDF::loadHTML($renderedHtml)
            ->setOption('margin-top', 0)
            ->setOption('margin-bottom', 0)
            ->setOption('margin-left', 0)
            ->setOption('margin-right', 0)
            ->setPaper('letter')
            ->output();

        return Response::make($pdf, 200, [
            'Content-Type'        => 'application/pdf',
            'Content-Disposition' => "filename=test.pdf",
        ]);
    }

quite simple, isn't it ? It's even simpler than the demo code as I don't load models, just want to render that small part of HTML.

When I click that button in backend, nothing happens, but I can see the "test" string on event log, so I'm sure the code in the function is red.

The strange thing is, if I replace -`>output()` by `->save('test.pdf')`, it correctly save the test.pdf file to the website root folder, and the PDF contain my "test h1", so it works.

But I don't want to generate a file on the server, I want to directly make the user to download the just generated PDF (seems that it's the purpose of your demo code), but it doesn't work.

Do you have any ideas ? As I have absolutely no feedback except my trace_log, I can't understand why your demo code doesn't work.

Thank you

Alex

**Comment by LukeTowers** [comment]
@Zmove AJAX handlers don't support returning file responses. You'd have to return a redirect to a controller action that returns the file response as a workaround because the AJAX framework does support handling redirects which lead to file responses.

**Comment by LukeTowers** [comment]
```php
public function onDownload() {
    return Redirect::to('/this/controller/download');
}

public function download() {
    trace_log('test');
    $renderedHtml = '<h1>Test</h1>';
    $pdf = SnappyPDF::loadHTML($renderedHtml)
        ->setOption('margin-top', 0)
        ->setOption('margin-bottom', 0)
        ->setOption('margin-left', 0)
        ->setOption('margin-right', 0)
        ->setPaper('letter')
        ->output();

    return Response::make($pdf, 200, [
        'Content-Type'        => 'application/pdf',
        'Content-Disposition' => "filename=test.pdf",
    ]);
}
