### ISSUE TITLE
Is not downloading?

### ISSUE THREAD

**Issue by briddle** [LukeTowers/oc-snappypdf-plugin#8]
This plugin stalls when downloading (installing from the backend of an October installation). Can anyone confirm this?

(I am installing on October 455 on PHP 7.0.8)

**Comment by briddle** [comment]
Took a looooong time but eventually downloaded

**Comment by LukeTowers** [comment]
@briddle this is because the plugin comes with the binaries pre installed, which ends up being a couple hundred MB.
